# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: amorcill <amorcill@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/23 12:57:35 by amorcill          #+#    #+#              #
#    Updated: 2021/06/23 12:57:37 by amorcill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = aLibft.out

SRC = main.c ft_memset.c test_memset.c

all: 
	gcc -o $(NAME) $(SRC) 

clean:
	/*.out

fclean: clean
	/

recompil: fclean all